baseURL = 'http://www.rationality-freiburg.de/'
languageCode = 'en-us'
title = 'Rationality Freiburg'
theme = 'zen'

[params]
contact = "info@rationality-freiburg.de"
description = "Meeting place for LessWrong and SCC readers, as well as other rationalists in and around Freiburg, Germany"
footer = "info@rationality-freiburg.de"
logo = true
realfavicongenerator = true
