baseURL = 'https://www.rationality-freiburg.de/'
languageCode = 'en-us'
title = 'Rationality Freiburg'
theme = 'zen'
defaultContentLanguage = 'en'

[params]
contact = "info@rationality-freiburg.de"
description = "Meeting place for LessWrong and SSC/ACX readers, as well as other rationalists in and around Freiburg im Breisgau, Germany"
footer = "info@rationality-freiburg.de"
logo = true
realfavicongenerator = true
mainSections = ["posts", "events"]

[markup.goldmark.renderer]
unsafe = true # enable html in markdown

[languages]

  [languages.en]
    weight = 1
    languageName = "English"
    languageCode = "en-US"
    contentDir = "content/en"

  [languages.de]
    weight = 2
    languageName = "Deutsch"
    languageCode = "de-DE"
    contentDir = "content/de"

    [languages.de.permalinks]
      events = "termine/:slug"
      posts = "beiträge/:slug"
